
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const LOGDB = 'LOGDB'
export const REDIS_CONNECTION = 'REDIS_CONNECTION'

export const DATABASE_CONNECTION = 'DATABASE_CONNECTION'
export const TESTING_REPOSITORY='TESTING_REPOSITORY'

export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_TEMP_REPOSITORY = 'USER_TEMP_REPOSITORY';
export const USER_DEVICE_REPOSITORY = 'USER_DEVICE_REPOSITORY';
export const PASSWORD_CONFIG_REPOSITORY = 'PASSWORD_CONFIG_REPOSITORY';
export const PROTOCOL_REPOSITORY = 'PROTOCOL_REPOSITORY';
export const COUNTRIES_REPOSITORY = 'COUNTRIES_REPOSITORY';